(in-package :fern)

(defun test ()
  (let ((scheduler1 (create-scheduler))
        (scheduler2 (create-scheduler))
        (printer nil)
        (process1 nil)
        (process2 nil))
    (setf printer (with-process (process :name "printer")
                    (with-messages process (msg)
                      (format t "~a~%" msg))))
    (setf process1 (with-process (process :name "process1")
                     (let ((msg-count 0))
                       (with-messages process (msg)
                         (message printer (format nil "~a: ~a" (process-name process) msg))
                         (incf msg-count)
                         (when (process-active-p process2)
                           (message process2 (format nil "~a, 1" msg)))
                         (when (< 2 msg-count)
                           (terminate process)))))
          process2 (with-process (process :name "process2")
                     (let ((msg-count 0))
                       (with-messages process (msg)
                         (message printer (format nil "~a: ~a" (process-name process) msg))
                         (when (process-active-p process1)
                           (message process1 (format nil "~a, 2" msg)))
                         (incf msg-count)
                         (when (< 2 msg-count)
                           (terminate process))))))
    (message process1 "hai")
    (message process2 "zzz")
    (sleep 1)
    (stop-scheduler scheduler1)
    (stop-scheduler scheduler2)
    (terminate printer)))


